const spaceFacts = [
  "A day on Venus is longer than its year.",
  "Neutron stars can spin 600 times per second.",
  "There may be a planet made entirely of diamonds.",
  "Saturn’s moon Titan has lakes of liquid methane.",
  "Jupiter’s Great Red Spot is a giant storm larger than Earth.",
  "The Sun makes up 99.86% of the mass in the Solar System.",
  "Footprints on the Moon will remain for millions of years.",
  "There is a massive water cloud in space with 140 trillion times the water in Earth's oceans.",
  "Mars has the tallest volcano in the solar system—Olympus Mons.",
  "One day on Mercury lasts about 59 Earth days.",
  "The Moon is slowly drifting away from Earth—about 1.5 inches per year.",
  "Pluto is smaller than the United States.",
  "A spoonful of a neutron star weighs about a billion tons.",
  "The Sun is a nearly perfect sphere.",
  "One million Earths could fit inside the Sun.",
  "A sunset on Mars appears blue.",
  "There are more stars in the universe than grains of sand on all Earth’s beaches.",
  "The largest known star is UY Scuti.",
  "There is a volcano on Mars three times taller than Mount Everest.",
  "Saturn could float in water because it is mostly made of gas.",
  "There are more trees on Earth than stars in the Milky Way.",
  "Space is completely silent due to lack of atmosphere.",
  "There is a giant cloud of alcohol in space.",
  "Black holes warp time and space around them.",
  "The coldest place in the universe is the Boomerang Nebula.",
  "Astronauts can grow up to 2 inches taller in space.",
  "The International Space Station orbits Earth every 90 minutes.",
  "Venus is the hottest planet in the Solar System.",
  "Some planets may have diamond rain.",
  "The Voyager 1 spacecraft has left the Solar System.",
  "The Kuiper Belt is home to dwarf planets like Pluto and Eris.",
  "The speed of light is 299,792 kilometers per second.",
  "Earth’s magnetic field protects it from solar wind.",
  "A year on Neptune is 165 Earth years long.",
  "Uranus rotates on its side.",
  "The Milky Way is on a collision course with Andromeda.",
  "A day on Jupiter is only 10 hours long.",
  "The Hubble Space Telescope was launched in 1990.",
  "There’s a planet where it rains molten glass sideways.",
  "The Moon has moonquakes.",
  "The ISS is the most expensive object ever built.",
  "NASA’s Perseverance rover is currently exploring Mars.",
  "A white dwarf is the leftover core of a dead star.",
  "Supernovae are the explosions of massive stars.",
  "The James Webb Space Telescope can see light from the early universe.",
  "Space travel can weaken your immune system.",
  "Astronauts' hearts become more spherical in space.",
  "Mars has seasons similar to Earth.",
  "Light from the Sun takes 8 minutes and 20 seconds to reach Earth.",
  "The Milky Way has a supermassive black hole at its center.",
  "The Moon has no atmosphere.",
  "There’s a hexagon-shaped storm on Saturn’s north pole.",
  "Solar flares can disrupt Earth's communications.",
  "There are rogue planets floating without a star.",
  "The Sun will eventually become a white dwarf.",
  "Gravity on the Moon is 1/6th that of Earth’s.",
  "Astronaut suits cost over $12 million each.",
  "The Moon was likely formed from a collision between Earth and a Mars-sized object.",
  "Venus rotates clockwise, unlike most planets.",
  "There are galaxies over 13 billion light years away.",
  "Some stars explode into supernovae and become neutron stars.",
  "Mars has two moons: Phobos and Deimos.",
  "The Milky Way is about 100,000 light years across.",
  "The ISS travels at about 17,500 mph.",
  "Halley’s Comet will return in 2061.",
  "The largest moon in the solar system is Ganymede.",
  "There is a planet where a year lasts only 18 hours.",
  "Some stars are older than the Milky Way galaxy.",
  "Astronauts use Velcro to keep things from floating away.",
  "There are more than 200 moons in our Solar System.",
  "The Oort Cloud is a distant shell of icy bodies around the solar system.",
  "Venus has mountains and volcanoes.",
  "The first human in space was Yuri Gagarin in 1961.",
  "No one can hear you scream in space—sound needs a medium.",
  "Planets around other stars are called exoplanets.",
  "Some exoplanets are thought to be Earth-like.",
  "The hottest planet is not closest to the Sun—it’s Venus.",
  "Gravity is weaker at the equator than the poles.",
  "Earth is the only planet not named after a god.",
  "Neptune has the fastest winds in the Solar System.",
  "Stars don’t twinkle in space—they do from Earth’s atmosphere.",
  "The first living creature in orbit was Laika the dog.",
  "The Kuiper Belt is like an asteroid belt but farther out.",
  "There’s a galaxy that looks like a sombrero.",
  "The far side of the Moon is not always dark—it gets sunlight too.",
  "Meteor showers are caused by debris from comets.",
  "Pulsars are spinning neutron stars that emit beams of light.",
  "The largest volcano in the Solar System is Olympus Mons.",
  "The space between galaxies is not empty—it contains gas and dust.",
  "The Milky Way rotates once every 225 million years.",
  "A black hole’s gravity is so strong not even light can escape.",
  "One day on Earth used to be only 6 hours long.",
  "The first moon landing was in 1969.",
  "Earth’s rotation is gradually slowing.",
  "Some telescopes can see through dust clouds using infrared.",
  "Galaxies come in spiral, elliptical, and irregular shapes.",
  "There’s a moon with a subsurface ocean—Europa.",
  "You age slightly slower at higher altitudes due to time dilation.",
  "There is a volcano on Io that constantly erupts.",
  "NASA was established in 1958.",
  "The Andromeda Galaxy is visible to the naked eye.",
  "The ISS has been continuously occupied since 2000.",
  "The term 'planet' means 'wanderer' in Greek.",
  "The longest continuous human spaceflight was 437 days.",
  "Astronauts can see 16 sunrises and sunsets a day from the ISS."
];
